project = 'Asystent Audytora'
author = 'Zespół'
extensions = ['myst_parser','sphinx.ext.autodoc','sphinx.ext.viewcode']
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'sphinx_rtd_theme'
myst_enable_extensions = ["deflist","colon_fence"]
html_title = 'Asystent Audytora — Dokumentacja'
html_static_path = ['_static']
