services:
  ai-auditor:
    build: .
    image: ai-auditor:cpu
    ports:
      - "8585:8501"
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      # - ./models:/app/models
    command: streamlit run app/Home.py --server.port=8501 --server.address=0.0.0.0
