name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit zero if there are no errors
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests
      run: |
        pytest tests/ -v --tb=short

    - name: Test imports
      run: |
        python -c "import streamlit; import requests; import pandas; print('✅ All imports successful')"

    - name: Check code formatting
      run: |
        pip install black
        black --check --diff .

  e2e-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Start backend server
      run: |
        uvicorn local_test.server:app --port 8000 --host 0.0.0.0 &
        sleep 10
        curl -f http://localhost:8000/healthz || exit 1

    - name: Run E2E tests
      run: |
        export RUN_E2E=1
        export BACKEND_URL="http://localhost:8000"
        export BASIC_AUTH_USER="user"
        export BASIC_AUTH_PASS="TwojPIN123!"
        pytest -m e2e -v tests/test_e2e.py

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          test-results/
          .pytest_cache/
