name: docs-pages
on:
  workflow_dispatch:
  push:
    branches: ["main","docs/**","ci/**","chore/**"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Sphinx
        run: |
          python -m pip install -U pip
          pip install sphinx myst-parser
      - name: Build docs
        run: sphinx-build -b html docs/sphinx _site
      - name: Verify artifact
        run: |
          test -f _site/index.html
          du -sh _site || true
          find _site -maxdepth 2 -type f | head -n 50
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
