name: gh-pages
on:
  workflow_dispatch:
  push:
    branches: ["main","docs/**","ci/**","chore/**"]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Sphinx
        run: |
          python -m pip install -U pip
          pip install sphinx myst-parser
      - name: Build docs
        run: sphinx-build -b html docs/sphinx _site
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true
