name: smoke-and-docs
on:
  push:
    branches: [ "main", "release/**", "feat/**", "docs/**", "chore/**" ]
  pull_request:
permissions:
  contents: read
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pandas openpyxl xlsxwriter; fi
      - name: Run smoke perf_200
        run: bash scripts/smoke_perf_200.sh
      - name: Pack run
        run: |
          RUN=$(ls -td web_runs/perf200_* | head -1)
          if [ -x scripts/pack_run_plus.sh ]; then bash scripts/pack_run_plus.sh "$RUN"; else bash scripts/pack_run.sh "$RUN"; fi
      - name: Upload smoke artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            web_runs/**/handoff_*.zip
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Sphinx
        run: |
          python -m pip install -U pip
          pip install sphinx myst-parser
      - name: Build docs
        run: sphinx-build -b html docs/sphinx docs/_build/html
      - name: Upload docs html
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

  tiebreak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pandas openpyxl xlsxwriter
      - name: Run A/B tiebreak
        run: bash scripts/smoke_tiebreak_ab.sh
      - name: Upload tiebreak artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tiebreak-artifacts
          path: |
            web_runs/tb_ab_*/v1.jsonl
            web_runs/tb_ab_*/v1_summary.json
          if-no-files-found: ignore
