[authentication]
password = "TwojPIN123!"

[cloudflare]
api_token = "your_token_here"
account_id = "your_account_id_here"
zone_id = "your_zone_id_here"
domain = "your-domain.com"

# AI Configuration for Streamlit Cloud
[ai]
server_url = "https://ai-auditor-romaks-8002.loca.lt"
timeout = 30
